/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import chartbrew from '@chartbrew/plugin-strapi/strapi-admin';
import contentVersioning from '@notum-cz/strapi-plugin-content-versioning/strapi-admin';
import calendar from '@offset-dev/strapi-calendar/strapi-admin';
import strapiAppVersion from '@palmabit/strapi-app-version/strapi-admin';
import strapiCloud from '@strapi/plugin-cloud/strapi-admin';
import documentation from '@strapi/plugin-documentation/strapi-admin';
import i18N from '@strapi/plugin-i18n/strapi-admin';
import usersPermissions from '@strapi/plugin-users-permissions/strapi-admin';
import contentTypeExplorer from 'strapi-content-type-explorer/strapi-admin';
import graphsBuilder from 'strapi-plugin-graphs-builder/strapi-admin';
import importExportEntries from 'strapi-plugin-import-export-entries/strapi-admin';
import restCache from 'strapi-plugin-rest-cache/strapi-admin';
import routePermission from 'strapi-plugin-server-route-permission/strapi-admin';
import { renderAdmin } from '@strapi/strapi/admin';

renderAdmin(document.getElementById('strapi'), {
  plugins: {
    chartbrew: chartbrew,
    'content-versioning': contentVersioning,
    calendar: calendar,
    'strapi-app-version': strapiAppVersion,
    'strapi-cloud': strapiCloud,
    documentation: documentation,
    i18n: i18N,
    'users-permissions': usersPermissions,
    'content-type-explorer': contentTypeExplorer,
    'graphs-builder': graphsBuilder,
    'import-export-entries': importExportEntries,
    'rest-cache': restCache,
    'route-permission': routePermission,
  },
});
